version: "3.7"

services:
  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@db/demo

  db:
    image: postgres:14.5
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=demo

volumes:
  postgres_data:
